# Generated by Django 6.0.6 on 2026-06-08 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_petit', models.CharField(max_length=200, verbose_name='Petit titre')),
                ('titre_principal', models.CharField(max_length=300, verbose_name='Titre principal')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(upload_to='carousel/principal/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Version optimisée mobile', null=True, upload_to='carousel/principal/mobile/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('position_image', models.CharField(choices=[('gauche', 'Image à gauche'), ('droite', 'Image à droite'), ('centre', 'Image centrée')], default='gauche', max_length=10)),
                ('couleur_fond', models.CharField(default='#1A1A2E', max_length=7)),
                ('couleur_titre', models.CharField(default='#FFFFFF', max_length=7)),
                ('couleur_bouton', models.CharField(default='#FF6B00', max_length=7)),
                ('texte_bouton', models.CharField(default='Shop Now', max_length=50)),
                ('lien_bouton', models.CharField(max_length=500)),
                ('ouvrir_nouvel_onglet', models.BooleanField(default=False)),
                ('texte_badge', models.CharField(blank=True, help_text='Ex: NOUVEAUTÉ, -50%, EXCLU', max_length=50)),
                ('couleur_badge', models.CharField(default='#FF3300', max_length=7)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('nb_clics', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide du carousel principal',
                'verbose_name_plural': 'Slides du carousel principal',
                'db_table': 'contenu_carousel_principal',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitesse_transition', models.PositiveIntegerField(default=3000, help_text='ms')),
                ('auto_play', models.BooleanField(default=True)),
                ('afficher_fleches', models.BooleanField(default=True)),
                ('afficher_points', models.BooleanField(default=True)),
                ('boucle', models.BooleanField(default=True)),
                ('effet_transition', models.CharField(choices=[('slide', 'Glissement'), ('fade', 'Fondu')], default='slide', max_length=10)),
                ('afficher_banniere_laterale', models.BooleanField(default=True)),
                ('rotation_banniere', models.BooleanField(default=False)),
                ('duree_banniere', models.PositiveIntegerField(default=5000, help_text='ms')),
                ('hauteur_carousel_desktop', models.PositiveIntegerField(default=500, help_text='px')),
                ('hauteur_carousel_mobile', models.PositiveIntegerField(default=300, help_text='px')),
                ('afficher_compteur_slides', models.BooleanField(default=False)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du carousel',
                'verbose_name_plural': 'Configuration du carousel',
                'db_table': 'contenu_config_carousel',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'db_table': 'contenu_tag',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BannierePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('smartphone', 'SmartPhone'), ('laptop', 'Laptop'), ('tablet', 'Tablette'), ('accessoire', 'Accessoire'), ('vetement', 'Vêtement'), ('electromenager', 'Électroménager'), ('autre', 'Autre')], default='smartphone', max_length=20)),
                ('nom_produit', models.CharField(max_length=200)),
                ('image_fond', models.ImageField(upload_to='carousel/banniere/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('prix_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_economie', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé automatiquement si vide', max_digits=10, null=True)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('titre_offre', models.CharField(default='Promotion du jour', max_length=100)),
                ('sous_titre', models.CharField(blank=True, max_length=200)),
                ('texte_bouton', models.CharField(default='Ajouter au panier', max_length=50)),
                ('lien_bouton', models.CharField(max_length=500)),
                ('est_actif', models.BooleanField(default=True)),
                ('priorite', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('nb_clics', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(blank=True, help_text='Lier à un produit ou remplir manuellement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannieres_promo', to='apps_core.produit')),
            ],
            options={
                'verbose_name': 'Bannière de promotion',
                'verbose_name_plural': 'Bannières de promotion',
                'db_table': 'contenu_banniere_promotion',
                'ordering': ['-priorite', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CategorieBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/')),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='apps_contenu.categorieblog')),
            ],
            options={
                'verbose_name': 'Catégorie Blog',
                'db_table': 'contenu_categorie_blog',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sous_titre', models.CharField(blank=True, max_length=250)),
                ('extrait', models.TextField(max_length=300)),
                ('contenu', models.TextField()),
                ('image_principale', models.ImageField(upload_to='blog/articles/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('type_article', models.CharField(choices=[('conseil', "Conseil d'achat"), ('innovation', 'Innovation technologique'), ('actualite', 'Actualité'), ('tutoriel', 'Tutoriel'), ('comparatif', 'Comparatif produits'), ('tendance', 'Tendance mode / tech')], default='actualite', max_length=20)),
                ('zone_geo', models.CharField(choices=[('local', 'Local'), ('international', 'International'), ('mixte', 'Local & International')], default='mixte', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('vues', models.PositiveIntegerField(default=0, editable=False)),
                ('featured', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('produits_lies', models.ManyToManyField(blank=True, help_text='Produits mentionnés / recommandés', related_name='articles', to='apps_core.produit')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='apps_contenu.categorieblog')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='apps_contenu.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'db_table': 'contenu_article',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000)),
                ('actif', models.BooleanField(default=True)),
                ('nb_likes', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='apps_contenu.article')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='apps_contenu.commentairearticle')),
            ],
            options={
                'db_table': 'contenu_commentaire_article',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(choices=[('slide', 'Slide principal'), ('banniere', 'Bannière promotion')], max_length=10)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('action', models.CharField(choices=[('vue', 'Vue'), ('clic', 'Clic')], default='clic', max_length=5)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('banniere_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='apps_contenu.bannierepromotion')),
                ('slide_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='apps_contenu.carouselprincipal')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique carousel',
                'db_table': 'contenu_stat_carousel',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ZoneLivraisonVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_active', models.BooleanField(default=True)),
                ('frais_personnalises', models.DecimalField(blank=True, decimal_places=2, help_text='Frais spéciaux pour cette ville', max_digits=10, null=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_livraison', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.ville')),
            ],
            options={
                'db_table': 'contenu_zone_livraison_vendeur',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-date_publication', 'statut'], name='contenu_art_date_pu_18e285_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='contenu_art_slug_f6d7ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonelivraisonvendeur',
            unique_together={('vendeur', 'ville')},
        ),
    ]
