# Generated by Django 6.0.6 on 2026-06-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        ('apps_marketplace', '0001_initial'),
        ('apps_social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepanier',
            name='produit_live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_social.produitlive'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_core.varianteproduit'),
        ),
        migrations.AddField(
            model_name='avisvendeur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avisvendeur',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='kyc_valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques_kyc_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boutique',
            name='vendeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avisvendeur',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_vendeur', to='apps_marketplace.boutique', verbose_name='Boutique (optionnel)'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='boutique',
            field=models.ForeignKey(blank=True, help_text='Null si vendeur individuel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_marketplace.boutique'),
        ),
        migrations.AddField(
            model_name='codepromo',
            name='categories_ciblees',
            field=models.ManyToManyField(blank=True, to='apps_core.categorie'),
        ),
        migrations.AddField(
            model_name='codepromo',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_promo_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codepromo',
            name='produits_cibles',
            field=models.ManyToManyField(blank=True, to='apps_core.produit'),
        ),
        migrations.AddField(
            model_name='codepromo',
            name='utilisateurs_cibles',
            field=models.ManyToManyField(blank=True, related_name='codes_promo_disponibles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='boutique',
            field=models.ForeignKey(blank=True, help_text='Boutique principale (null si vendeur individuel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='apps_marketplace.boutique'),
        ),
        migrations.AddField(
            model_name='commande',
            name='code_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='apps_marketplace.codepromo'),
        ),
        migrations.AddField(
            model_name='commande',
            name='promotions_appliquees',
            field=models.ManyToManyField(blank=True, to='apps_core.promotion'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quartier_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_core.quartier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='apps_core.ville'),
        ),
        migrations.AddField(
            model_name='avisvendeur',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='demandevendeur',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandevendeur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_vendeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentkyc',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_kyc', to='apps_marketplace.boutique'),
        ),
        migrations.AddField(
            model_name='employeboutique',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='apps_marketplace.boutique'),
        ),
        migrations.AddField(
            model_name='employeboutique',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_boutique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupeachat',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupeachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_achat', to='apps_core.produit'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='groupe_achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_marketplace.groupeachat'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquelivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='apps_marketplace.livraison'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='methode_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_marketplace.methodelivraison'),
        ),
        migrations.AddField(
            model_name='numeroversement',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='apps_core.pays'),
        ),
        migrations.AddField(
            model_name='numeroversement',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='apps_marketplace.operateur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='apps_marketplace.panier'),
        ),
        migrations.AddField(
            model_name='participantgroupeachat',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='participantgroupeachat',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='apps_marketplace.groupeachat'),
        ),
        migrations.AddField(
            model_name='participantgroupeachat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planpaiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_paiement', to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='retour',
            name='article_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_marketplace.articlecommande'),
        ),
        migrations.AddField(
            model_name='retour',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='retour',
            name='photos',
            field=models.ManyToManyField(blank=True, to='apps_core.imageavis'),
        ),
        migrations.AddField(
            model_name='retour',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tranchepaiement',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranche', to='apps_marketplace.paiement'),
        ),
        migrations.AddField(
            model_name='tranchepaiement',
            name='plan_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='apps_marketplace.planpaiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='tranche_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps_marketplace.tranchepaiement'),
        ),
        migrations.AlterUniqueTogether(
            name='avisvendeur',
            unique_together={('vendeur', 'utilisateur', 'commande')},
        ),
        migrations.AlterUniqueTogether(
            name='employeboutique',
            unique_together={('boutique', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='articlepanier',
            unique_together={('panier', 'produit', 'variante')},
        ),
        migrations.AlterUniqueTogether(
            name='participantgroupeachat',
            unique_together={('groupe', 'utilisateur')},
        ),
    ]
