# Generated by Django 6.0.6 on 2026-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecommande',
            name='wallet_credite',
            field=models.BooleanField(default=False, help_text='True quand les fonds ont été versés au(x) vendeur(s)', verbose_name='Wallet vendeur crédité'),
        ),
    ]
