# Generated by Django 6.0.6 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevente',
            name='stream_demarre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livevente',
            name='stream_statut',
            field=models.CharField(choices=[('hors_ligne', '⚫ Hors ligne'), ('connexion', '🟡 Connexion en cours'), ('diffusion', '🔴 En diffusion'), ('erreur', '⚠️ Erreur de connexion'), ('termine', '⏹️ Diffusion terminée')], default='hors_ligne', max_length=20),
        ),
    ]
