# Generated by Django 6.0.6 on 2026-06-14 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRechargeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('wave', 'Wave'), ('carte_bancaire', 'Carte bancaire')], max_length=30)),
                ('numero_expediteur', models.CharField(blank=True, max_length=30)),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='recharges/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('note_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recharge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de recharge',
                'db_table': 'core_demande_recharge',
                'ordering': ['-date_creation'],
            },
        ),
    ]
