# Generated by Django 6.0.6 on 2026-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0002_demanderechargewallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='bannieres/', verbose_name='Bannière de profil'),
        ),
    ]
