# Generated by Django 6.0.6 on 2026-06-08 11:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleAuction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('nom_camp_a', models.CharField(default='Camp A', max_length=100)),
                ('nom_camp_b', models.CharField(default='Camp B', max_length=100)),
                ('couleur_camp_a', models.CharField(default='#0066FF', max_length=7)),
                ('couleur_camp_b', models.CharField(default='#FF3300', max_length=7)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_venir', max_length=15)),
                ('nb_supporters_a', models.PositiveIntegerField(default=0)),
                ('nb_supporters_b', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Battle Auction',
                'db_table': 'enchere_battle_auction',
            },
        ),
        migrations.CreateModel(
            name='EnchereFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_minutes', models.PositiveIntegerField(choices=[(5, '⚡ 5 minutes'), (10, '⚡ 10 minutes'), (30, '⚡ 30 minutes'), (60, '⚡ 1 heure'), (120, '⚡ 2 heures')], default=30)),
                ('extension_par_offre_secondes', models.PositiveIntegerField(default=30, help_text='Secondes ajoutées à chaque offre dans la dernière minute')),
                ('afficher_timer_geant', models.BooleanField(default=True)),
                ('couleur_urgence', models.CharField(default='#FF0000', help_text='Couleur du timer quand < 60s', max_length=7)),
                ('nb_acheteurs_max', models.PositiveIntegerField(blank=True, help_text='Limite optionnelle de participants', null=True)),
            ],
            options={
                'verbose_name': 'Config Enchère Flash',
                'db_table': 'enchere_flash',
            },
        ),
        migrations.CreateModel(
            name='EnchereGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_totale', models.PositiveIntegerField(help_text='Quantité totale du lot')),
                ('quantite_min_par_participant', models.PositiveIntegerField(default=1)),
                ('quantite_max_par_participant', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_participants_min', models.PositiveIntegerField(default=2)),
                ('nb_participants_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Config Enchère Groupe',
                'db_table': 'enchere_groupe_config',
            },
        ),
        migrations.CreateModel(
            name='EstimationPrixIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_estime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_min_suggere', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_max_suggere', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_moyen_marche', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_moyen_encheres_historiques', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('score_demande', models.DecimalField(decimal_places=2, default=0, help_text='0-10 : demande actuelle', max_digits=5)),
                ('facteur_etat', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicateur selon état du produit', max_digits=5)),
                ('tendance_marche', models.CharField(choices=[('hausse', 'En hausse'), ('stable', 'Stable'), ('baisse', 'En baisse')], default='stable', max_length=20)),
                ('confiance_estimation', models.DecimalField(decimal_places=2, default=0, help_text="% de confiance de l'IA (0-100)", max_digits=5)),
                ('explication', models.TextField(blank=True, help_text="Explication lisible de l'estimation")),
                ('date_estimation', models.DateTimeField(auto_now_add=True)),
                ('version_modele_ia', models.CharField(default='v1.0', max_length=50)),
            ],
            options={
                'verbose_name': 'Estimation IA',
                'db_table': 'enchere_estimation_ia',
                'ordering': ['-date_estimation'],
            },
        ),
        migrations.CreateModel(
            name='InteractionSocialeEnchere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('like', '❤️ Like'), ('partage', '🔗 Partage'), ('commentaire', '💬 Commentaire')], max_length=15)),
                ('contenu', models.TextField(blank=True, help_text='Pour les commentaires')),
                ('plateforme_partage', models.CharField(blank=True, help_text='WhatsApp, Facebook, etc.', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enchere_interaction_sociale',
            },
        ),
        migrations.CreateModel(
            name='OffreEnchere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_offre_auto', models.BooleanField(default=False, verbose_name='Offre automatique (Smart Bid)')),
                ('montant_max_auto', models.DecimalField(blank=True, decimal_places=2, help_text='Budget max pour le Smart Bid', max_digits=12, null=True)),
                ('budget_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priorite_achat', models.PositiveIntegerField(default=5, help_text='1=basse, 10=haute', validators=[django.core.validators.MinValueValidator(1)])),
                ('est_achat_immediat', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enchere_offre',
                'ordering': ['-montant', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('delai_livraison', models.PositiveIntegerField(help_text='Jours')),
                ('garantie', models.CharField(blank=True, max_length=100)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='offres_vendeurs/')),
                ('est_selectionnee', models.BooleanField(default=False)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enchere_offre_vendeur',
                'ordering': ['montant'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantEnchereGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_souhaitee', models.PositiveIntegerField(default=1)),
                ('montant_offert', models.DecimalField(decimal_places=2, max_digits=12)),
                ('a_confirme', models.BooleanField(default=False)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enchere_participant_groupe',
            },
        ),
        migrations.CreateModel(
            name='SuccesEnchere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_succes', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('icone', models.CharField(default='🏆', max_length=10)),
                ('points_bonus', models.PositiveIntegerField(default=0)),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enchere_succes',
            },
        ),
        migrations.CreateModel(
            name='SupportBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.CharField(choices=[('a', 'Camp A'), ('b', 'Camp B')], max_length=1)),
                ('date_choix', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enchere_support_battle',
            },
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('specifications', models.JSONField(default=dict, help_text='Specs techniques JSON')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('est_b2b', models.BooleanField(default=False)),
                ('date_limite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert aux offres'), ('ferme', 'Fermé'), ('adjuge', 'Adjugé'), ('annule', 'Annulé')], default='ouvert', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offre', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.categorie')),
            ],
            options={
                'verbose_name': "Appel d'offre",
                'db_table': 'enchere_appel_offre',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ClassementEncherisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('semaine', 'Cette semaine'), ('mois', 'Ce mois'), ('total', 'Tout temps')], max_length=10)),
                ('annee', models.PositiveIntegerField()),
                ('numero_periode', models.PositiveIntegerField(help_text='Numéro de semaine ou mois')),
                ('rang', models.PositiveIntegerField()),
                ('nb_encheres', models.PositiveIntegerField(default=0)),
                ('nb_victoires', models.PositiveIntegerField(default=0)),
                ('montant_total_enchere', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('points_gagnes', models.PositiveIntegerField(default=0)),
                ('trophee', models.CharField(blank=True, help_text='Trophée attribué (top 3)', max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements_enchere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enchere_classement',
                'ordering': ['rang'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireEnchere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=500)),
                ('est_epingle', models.BooleanField(default=False)),
                ('nb_likes', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='apps_encheres.commentaireenchere')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enchere_commentaire',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ConfigSmartBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget maximum absolu')),
                ('budget_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priorite', models.PositiveIntegerField(default=5)),
                ('strategie', models.CharField(choices=[('progressive', 'Progressive (évite surpayer)'), ('aggressive', "Agressive (s'impose rapidement)"), ('last_second', 'Dernière seconde (snipe)')], default='progressive', max_length=20)),
                ('est_active', models.BooleanField(default=True)),
                ('depense_jour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config Smart Bid',
                'db_table': 'enchere_config_smart_bid',
            },
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_enchere', models.CharField(choices=[('classique', 'Classique'), ('flash', '⚡ Flash (durée limitée)'), ('video_live', '📹 Vidéo Live'), ('groupe', '👥 Groupe (lot partageable)'), ('inversee', '🔄 Inversée (vendeurs en compétition)'), ('battle', '⚔️ Battle Auction (2 produits vs)'), ('services', '🔧 Services / Projets'), ('stock_entier', '📦 Stock entier (B2B)'), ('objectif', '🎯 À objectif')], default='classique', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='encheres/couvertures/')),
                ('prix_depart', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_reserve', models.DecimalField(blank=True, decimal_places=2, help_text='Prix minimum secret', max_digits=12, null=True)),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_achat_immediat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_achat_immediat_initial', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('increment_minimum', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('extension_automatique', models.BooleanField(default=True, help_text='Prolonge si enchère dans les 30 dernières secondes')),
                ('duree_extension_secondes', models.PositiveIntegerField(default=30, help_text="Secondes ajoutées lors d'une extension")),
                ('nb_prolongations', models.PositiveIntegerField(default=0)),
                ('nb_prolongations_max', models.PositiveIntegerField(default=10)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', '🔴 En cours'), ('terminee', '✅ Terminée'), ('annulee', '❌ Annulée'), ('prolongee', '⏳ Prolongée')], default='a_venir', max_length=15)),
                ('montant_objectif', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('action_si_non_atteint', models.CharField(choices=[('annuler', 'Annuler'), ('prolonger', 'Prolonger automatiquement'), ('vente_directe', 'Basculer en vente directe')], default='annuler', max_length=20)),
                ('prix_estime_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Prix estimé par l'IA")),
                ('facteurs_estimation', models.JSONField(blank=True, default=dict, help_text="Facteurs pris en compte par l'IA")),
                ('points_participation', models.PositiveIntegerField(default=5, help_text='Points gagnés en enchérissant')),
                ('points_victoire', models.PositiveIntegerField(default=50)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('nb_likes', models.PositiveIntegerField(default=0)),
                ('nb_partages', models.PositiveIntegerField(default=0)),
                ('nb_offres', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encheres_gagnees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enchère',
                'db_table': 'enchere_enchere',
                'ordering': ['-date_creation'],
            },
        ),
    ]
