# Generated by Django 6.0.6 on 2026-06-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        ('apps_encheres', '0001_initial'),
        ('apps_marketplace', '0001_initial'),
        ('apps_social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enchere',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encheres_live', to='apps_social.livevente'),
        ),
        migrations.AddField(
            model_name='enchere',
            name='produit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enchere', to='apps_core.produit'),
        ),
        migrations.AddField(
            model_name='enchere',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encheres_vendeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configsmartbid',
            name='enchere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_bids', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='commentaireenchere',
            name='enchere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='battleauction',
            name='enchere_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_camp_a', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='battleauction',
            name='enchere_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_camp_b', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='enchereflash',
            name='enchere',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_flash', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='encheregroupe',
            name='enchere',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_groupe', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='estimationprixia',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations_ia', to='apps_core.produit'),
        ),
        migrations.AddField(
            model_name='interactionsocialeenchere',
            name='enchere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_sociales', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='interactionsocialeenchere',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offreenchere',
            name='enchere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='apps_encheres.enchere'),
        ),
        migrations.AddField(
            model_name='offreenchere',
            name='encherisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_enchere', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offrevendeur',
            name='appel_offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_vendeurs', to='apps_encheres.appeloffre'),
        ),
        migrations.AddField(
            model_name='offrevendeur',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_vendeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='offre_gagnante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_gagnes', to='apps_encheres.offrevendeur'),
        ),
        migrations.AddField(
            model_name='participantencheregroupe',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_marketplace.commande'),
        ),
        migrations.AddField(
            model_name='participantencheregroupe',
            name='enchere_groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='apps_encheres.encheregroupe'),
        ),
        migrations.AddField(
            model_name='participantencheregroupe',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='succesenchere',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succes_enchere', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportbattle',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='apps_encheres.battleauction'),
        ),
        migrations.AddField(
            model_name='supportbattle',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classementencherisseur',
            unique_together={('utilisateur', 'periode', 'annee', 'numero_periode')},
        ),
        migrations.AlterUniqueTogether(
            name='configsmartbid',
            unique_together={('utilisateur', 'enchere')},
        ),
        migrations.AlterUniqueTogether(
            name='offreenchere',
            unique_together={('enchere', 'encherisseur', 'montant')},
        ),
        migrations.AlterUniqueTogether(
            name='offrevendeur',
            unique_together={('appel_offre', 'vendeur')},
        ),
        migrations.AlterUniqueTogether(
            name='participantencheregroupe',
            unique_together={('enchere_groupe', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='supportbattle',
            unique_together={('battle', 'utilisateur')},
        ),
    ]
